/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DeviceDeviceIdImport } from './routes/device/$deviceId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DeviceDeviceIdRoute = DeviceDeviceIdImport.update({
  id: '/device/$deviceId',
  path: '/device/$deviceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/device/$deviceId': {
      id: '/device/$deviceId'
      path: '/device/$deviceId'
      fullPath: '/device/$deviceId'
      preLoaderRoute: typeof DeviceDeviceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/device/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/device/$deviceId'
  id: '__root__' | '/' | '/device/$deviceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeviceDeviceIdRoute: typeof DeviceDeviceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeviceDeviceIdRoute: DeviceDeviceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/device/$deviceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/device/$deviceId": {
      "filePath": "device/$deviceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
