/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardLogsImport } from './routes/dashboard/logs'
import { Route as DashboardDeviceIdImport } from './routes/dashboard/$deviceId'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLogsRoute = DashboardLogsImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDeviceIdRoute = DashboardDeviceIdImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/$deviceId': {
      id: '/dashboard/$deviceId'
      path: '/$deviceId'
      fullPath: '/dashboard/$deviceId'
      preLoaderRoute: typeof DashboardDeviceIdImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardDeviceIdRoute: typeof DashboardDeviceIdRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDeviceIdRoute: DashboardDeviceIdRoute,
  DashboardLogsRoute: DashboardLogsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$deviceId': typeof DashboardDeviceIdRoute
  '/dashboard/logs': typeof DashboardLogsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$deviceId': typeof DashboardDeviceIdRoute
  '/dashboard/logs': typeof DashboardLogsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$deviceId': typeof DashboardDeviceIdRoute
  '/dashboard/logs': typeof DashboardLogsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/dashboard/$deviceId' | '/dashboard/logs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/dashboard/$deviceId' | '/dashboard/logs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/$deviceId'
    | '/dashboard/logs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/$deviceId",
        "/dashboard/logs"
      ]
    },
    "/dashboard/$deviceId": {
      "filePath": "dashboard/$deviceId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/logs": {
      "filePath": "dashboard/logs.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
